# Generated by Django 2.0.6 on 2019-12-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llavePrivada', models.CharField(default='', max_length=200)),
                ('llavePublica', models.CharField(default='', max_length=200)),
                ('balance', models.IntegerField(verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eMail', models.CharField(default='', max_length=200)),
                ('contrasenia', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='walle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Wallet'),
        ),
    ]
